name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    strategy:
      fail-fast: false
      matrix:
        config:

          - name: "Linux GCC"
            os: ubuntu-24.04
            shell: bash
            package_name: "linux_amd64"
            artifact-path: build/*
            
          - name: "Linux Clang"
            os: ubuntu-24.04
            shell: bash
            extra_options: "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install \
        libfluidsynth-dev libwebkit2gtk-4.1-dev libwebp-dev \
        libftgl-dev liblua5.3-dev libmpg123-dev libsfml-dev \
        libwxgtk3.2-dev libwxgtk-webview3.2-dev

    - name: Configure
      run: |
        mkdir build
        cmake -B build ${{ matrix.config.extra_options }} .

    - name: Build
      run: |
        export MAKEFLAGS=--keep-going
        cmake --build build --parallel 3

    
    - name: Upload Artifacts
      if: ${{ matrix.config.package_name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config.package_name }}
        path: ${{ matrix.config.artifact-path }}
